/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameMgr_CloudFlame from "./Mgr/GameMgr"
import GameOver from "./View/GameOver/GameOver"
import RoleSkin from "./View/GameStart/RoleSkin"
import GameStart from "./View/GameStart/GameStart"
import ViewAutoScale from "./View/ViewAutoScale"
import Gaming from "./View/Gaming/Gaming"
import LoadingView from "./View/LoadingView"
import TipsView from "./View/TipsView/TipsView"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="GameMain.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("Mgr/GameMgr.ts",GameMgr_CloudFlame);
        reg("View/GameOver/GameOver.ts",GameOver);
        reg("View/GameStart/RoleSkin.ts",RoleSkin);
        reg("View/GameStart/GameStart.ts",GameStart);
        reg("View/ViewAutoScale.ts",ViewAutoScale);
        reg("View/Gaming/Gaming.ts",Gaming);
        reg("View/LoadingView.ts",LoadingView);
        reg("View/TipsView/TipsView.ts",TipsView);
    }
}
GameConfig.init();